name: Check unimplemented_v2 calls


on:
  pull_request:
    paths:
      - 'torch/_dynamo/*.py'
      - 'torch/_dynamo/**/*.py'

jobs:
  check-unimplemented-calls:
    if: github.repository_owner == 'pytorch'
    name: check-unimplemented-calls
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      build-environment: linux-jammy-py3.9-gcc11
      docker-image-name: ci-image:pytorch-linux-jammy-py3.9-gcc11
      test-matrix: |
        { include: [
          { config: "check_unimplemented_calls", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.2xlarge" }
        ]}
    secrets: inherit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
