name: pull

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  llm-td:
    name: before-test
    uses: ./.github/workflows/llm_td_retrieval.yml
    permissions:
      id-token: write
      contents: read

  target-determination:
    name: before-test
    uses: ./.github/workflows/target_determination.yml
    needs: llm-td
    permissions:
      id-token: write
      contents: read

  get-label-type:
    name: get-label-type
    uses: ./.github/workflows/_runner-determinator.yml
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}

  linux-jammy-py3_8-gcc11-build:
    name: linux-jammy-py3.8-gcc11
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-jammy-py3.8-gcc11
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "docs_test", shard: 1, num_shards: 1,  runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "jit_legacy", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "backwards_compat", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "distributed", shard: 1, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "distributed", shard: 2, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
        ]}

  linux-jammy-py3_8-gcc11-test:
    name: linux-jammy-py3.8-gcc11
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-jammy-py3_8-gcc11-build
      - target-determination
    with:
      build-environment: linux-jammy-py3.8-gcc11
      docker-image: ${{ needs.linux-jammy-py3_8-gcc11-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-py3_8-gcc11-build.outputs.test-matrix }}

  linux-docs:
    name: linux-docs
    uses: ./.github/workflows/_docs.yml
    needs: linux-jammy-py3_8-gcc11-build
    with:
      build-environment: linux-jammy-py3.8-gcc11
      docker-image: ${{ needs.linux-jammy-py3_8-gcc11-build.outputs.docker-image }}

  linux-jammy-py3_8-gcc11-no-ops:
    name: linux-jammy-py3.8-gcc11-no-ops
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-jammy-py3.8-gcc11-no-ops
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1 },
        ]}

  linux-jammy-py3_8-gcc11-pch:
    name: linux-jammy-py3.8-gcc11-pch
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-jammy-py3.8-gcc11-pch
      docker-image-name: pytorch-linux-jammy-py3.8-gcc11
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1 },
        ]}


  linux-jammy-py3_10-clang15-asan-build:
    name: linux-jammy-py3.10-clang15-asan
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-jammy-py3.10-clang15-asan
      docker-image-name: pytorch-linux-jammy-py3-clang15-asan
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 6, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.4xlarge" },
          { config: "default", shard: 2, num_shards: 6, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.4xlarge" },
          { config: "default", shard: 3, num_shards: 6, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.4xlarge" },
          { config: "default", shard: 4, num_shards: 6, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.4xlarge" },
          { config: "default", shard: 5, num_shards: 6, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.4xlarge" },
          { config: "default", shard: 6, num_shards: 6, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.4xlarge" },
        ]}
      sync-tag: asan-build


  linux-jammy-py3_10-clang15-asan-test:
    name: linux-jammy-py3.10-clang15-asan
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-jammy-py3_10-clang15-asan-build
      - target-determination
    with:
      build-environment: linux-jammy-py3.10-clang15-asan
      docker-image: ${{ needs.linux-jammy-py3_10-clang15-asan-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-py3_10-clang15-asan-build.outputs.test-matrix }}
      sync-tag: asan-test

  linux-focal-py3_8-clang10-onnx-build:
    name: linux-focal-py3.8-clang10-onnx
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-focal-py3.8-clang10-onnx
      docker-image-name: pytorch-linux-focal-py3-clang10-onnx
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
        ]}

  linux-focal-py3_8-clang10-onnx-test:
    name: linux-focal-py3.8-clang10-onnx
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-focal-py3_8-clang10-onnx-build
      - target-determination
    with:
      build-environment: linux-focal-py3.8-clang10-onnx
      docker-image: ${{ needs.linux-focal-py3_8-clang10-onnx-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-py3_8-clang10-onnx-build.outputs.test-matrix }}

  linux-focal-py3_8-clang10-build:
    name: linux-focal-py3.8-clang10
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-focal-py3.8-clang10
      docker-image-name: pytorch-linux-focal-py3.8-clang10
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "crossref", shard: 1, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "dynamo", shard: 1, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "dynamo", shard: 2, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "dynamo", shard: 3, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
        ]}

  linux-focal-py3_8-clang10-test:
    name: linux-focal-py3.8-clang10
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-focal-py3_8-clang10-build
      - target-determination
    with:
      build-environment: linux-focal-py3.8-clang10
      docker-image: ${{ needs.linux-focal-py3_8-clang10-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-py3_8-clang10-build.outputs.test-matrix }}

  linux-focal-py3_11-clang10-build:
    name: linux-focal-py3.11-clang10
    uses: ./.github/workflows/_linux-build-label.yml
    needs: get-label-type
    with:
      runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge"
      build-environment: linux-focal-py3.11-clang10
      docker-image-name: pytorch-linux-focal-py3.11-clang10
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "default", shard: 4, num_shards: 4, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "crossref", shard: 1, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 2, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "dynamo", shard: 1, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "dynamo", shard: 2, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
          { config: "dynamo", shard: 3, num_shards: 3, runner: "${{ needs.get-label-type.outputs.label-type }}c.linux.2xlarge" },
        ]}

  linux-focal-py3_11-clang10-test:
    name: linux-focal-py3.11-clang10
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-focal-py3_11-clang10-build
      - target-determination
    with:
      build-environment: linux-focal-py3.11-clang10
      docker-image: ${{ needs.linux-focal-py3_11-clang10-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-py3_11-clang10-build.outputs.test-matrix }}
